# Generated by Django 5.1.3 on 2024-12-30 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, 'Unusable'), (2, 'Bad'), (3, 'Ok'), (4, 'Good'), (5, 'Excellent')])),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=2000)),
                ('product', models.ManyToManyField(related_name='product_comment', to='main.product')),
                ('user', models.ManyToManyField(related_name='user_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
