# Generated by Django 5.1.3 on 2024-12-30 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ManyToManyField(related_name='product_review', to='main.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ManyToManyField(related_name='user_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
