# Generated by Django 5.1.3 on 2024-12-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_review_product_alter_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.CharField(default='aa', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.CharField(default='aa', max_length=20),
        ),
    ]
