# Generated by Django 5.1.3 on 2025-01-01 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
